### ISSUE TITLE
Deleted User Throws Error in Discussion List

### ISSUE THREAD

**Issue by glowingblue-dev** [ReFlar/level-ranks#10]
Hi,

The existence of an user is not checked properly before adding level ranks which leads to empty discussion list. The error is `Uncaught TypeError: t.commentCount is not a function` .

Once I have deactivated this extension, it worked again.

Running latest Flarum beta version and also your latest extension.

<img width="1343" alt="deleted_user_level_ranks" src="https://user-images.githubusercontent.com/36635329/59780407-3c045500-92ba-11e9-8905-48eabc205bda.png">

**Comment by Ralkage** [comment]
@glowingblue thank you for the report, we will look into it as soon as we can :)

**Comment by JC-ProPlus** [comment]
same issue = =

**Comment by Ralkage** [comment]
Hi @glowingblue and @JC-ProPlus, this issue was [fixed in the recent release](https://github.com/ReFlar/level-ranks/commit/8dd2e8bc07ff679110691301a17e04e1de67176e), please update to the latest release. If the issue still persists, feel free to open a new issue at any time :)
