### ISSUE TITLE
Migration Plan to FoF Namespace

### ISSUE THREAD

**Issue by Ralkage** [ReFlar/level-ranks#11]
TBD.

**Comment by Ralkage** [comment]
@datitisev should we still proceed with the migration or just archive it at this point?

**Comment by dsevillamartin** [comment]
@Ralkage I think we should make a FoF alternative where you can actually configure things.

**Comment by Ralkage** [comment]
@datitisev agreed, not sure if we just wait to abandon this extension after we make an alternative or just abandon/archive it now tbh

**Comment by dsevillamartin** [comment]
@Ralkage Eh, one could build off of this one. I'd abandon this one after an alternative exists.

**Comment by Ralkage** [comment]
Sounds like a plan! No use in keeping this issue open :P
