### ISSUE TITLE
gives role on the level

### ISSUE THREAD

**Issue by ghost** [ReFlar/level-ranks#14]
Do you make a system that gives role based on the level?
Sample;
For 10 level and above members; apprentice member
For 25 level and above members; senior member
For 50 level and above members; expert member
so so.

**Comment by Ralkage** [comment]
I understand that this is a highly requested feature, but this extension is currently only being maintained on an as-needed basis until another extension replaces it with more advanced features and functionality.

Thank you for your time and patience and to those who still watch this repo 🙇
